tasks:
  - name: zig
    init: ./tools/update-tools.sh
    command:
      export PATH=./tools/zig:$PATH
      && echo
      && echo workspace start - zig build run ...
      && zig build run

vscode:
  extensions:
    - tiehuis.zig@0.2.5:Yj8BTORJw/zERdoSGPf+eQ==